"""Lap comparison and driver-performance analysis."""

from f1pi.analysis.lap_analysis import LapComparisonEngine
from f1pi.analysis.models import (
    AnalysisQuality,
    ComparisonSummary,
    Confidence,
    CornerComparison,
    CornerPhaseKind,
    DriverCornerMetrics,
    DriverStraightMetrics,
    FindingEvidence,
    FindingKind,
    LapComparison,
    LapExplanation,
    LapSelection,
    LapSummary,
    PerformanceSectionComparison,
    PhaseComparison,
    SectionKind,
    SectorComparison,
    SegmentationConfig,
    SegmentationSource,
    StraightComparison,
    SummaryFinding,
    SynchronizationConfig,
    TurnComparison,
    TurnReference,
)
from f1pi.analysis.summary import SummaryNarrativeProvider

__all__ = [
    "AnalysisQuality",
    "ComparisonSummary",
    "Confidence",
    "CornerComparison",
    "CornerPhaseKind",
    "DriverCornerMetrics",
    "DriverStraightMetrics",
    "FindingEvidence",
    "FindingKind",
    "LapComparison",
    "LapComparisonEngine",
    "LapExplanation",
    "LapSelection",
    "LapSummary",
    "PerformanceSectionComparison",
    "PhaseComparison",
    "SectionKind",
    "SectorComparison",
    "SegmentationConfig",
    "SegmentationSource",
    "StraightComparison",
    "SummaryFinding",
    "SummaryNarrativeProvider",
    "SynchronizationConfig",
    "TurnComparison",
    "TurnReference",
]
