"""Lap comparison and driver-performance analysis."""

from f1pi.analysis.lap_analysis import LapComparisonEngine
from f1pi.analysis.models import (
    AnalysisQuality,
    ComparisonSummary,
    CompoundDegradationEstimate,
    Confidence,
    CornerComparison,
    CornerPhaseKind,
    DegradationMode,
    DriverCornerMetrics,
    DriverStraightMetrics,
    DriverTireDegradationAnalysis,
    DriverTireModelConfig,
    FindingEvidence,
    FindingKind,
    LapComparison,
    LapExplanation,
    LapSelection,
    LapSummary,
    PerformanceSectionComparison,
    PhaseComparison,
    SectionKind,
    SectorComparison,
    SegmentationConfig,
    SegmentationSource,
    StraightComparison,
    SummaryFinding,
    SynchronizationConfig,
    TireDegradationAnalysis,
    TireModelConfig,
    TireModelMetrics,
    TireModelValidation,
    TireStintSummary,
    TurnComparison,
    TurnReference,
)
from f1pi.analysis.performance_summary import SummaryNarrativeProvider
from f1pi.analysis.tire_model import TireDegradationEngine

__all__ = [
    "AnalysisQuality",
    "ComparisonSummary",
    "CompoundDegradationEstimate",
    "Confidence",
    "CornerComparison",
    "CornerPhaseKind",
    "DegradationMode",
    "DriverCornerMetrics",
    "DriverStraightMetrics",
    "DriverTireDegradationAnalysis",
    "DriverTireModelConfig",
    "FindingEvidence",
    "FindingKind",
    "LapComparison",
    "LapComparisonEngine",
    "LapExplanation",
    "LapSelection",
    "LapSummary",
    "PerformanceSectionComparison",
    "PhaseComparison",
    "SectionKind",
    "SectorComparison",
    "SegmentationConfig",
    "SegmentationSource",
    "StraightComparison",
    "SummaryFinding",
    "SummaryNarrativeProvider",
    "SynchronizationConfig",
    "TireDegradationAnalysis",
    "TireDegradationEngine",
    "TireModelConfig",
    "TireModelMetrics",
    "TireModelValidation",
    "TireStintSummary",
    "TurnComparison",
    "TurnReference",
]
